apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-app
  labels:
    app: anime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anime
  template:
    metadata:
      labels:
        app: anime
    spec:
      containers:
      - name: anime-container
        image: anime-app:latest  # Use local image
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8501
        envFrom:
          - secretRef:
              name: anime-secrets 

---
apiVersion: v1
kind: Service
metadata:
  name: anime-service
spec:
  type: LoadBalancer
  selector:
    app: anime
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501